name: Makefile CI

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-go@v3
        with:
          go-version: '1.19'

      - name: Install dependencies
        run: |
          go mod download
      - name: Run Unit tests
        run: |
          go test -race -covermode atomic -coverprofile=covprofile ./...
      - name: Install goveralls
        run: go install github.com/mattn/goveralls@latest
      - name: Send coverage
        shell: bash
        env:
          COVERALLS_TOKEN: ${{ secrets.COVERALLS_TOKEN }}
          COVERALLS_REPO_TOKEN: ${{ secrets.COVERALLS_TOKEN }}
        run: |
          goveralls -coverprofile=covprofile -service=github -debug
